In [1]:
from sqlalchemy import create_engine, text
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
engine = create_engine(f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}")

xls = pd.ExcelFile("C:\\Users\\sniks\\OneDrive\\Desktop\\dbms\\project\\data\\Supply chain logisitcs problem.xlsx")

orders = pd.read_excel(xls, "OrderList")
freight = pd.read_excel(xls, "FreightRates")
wh_costs = pd.read_excel(xls, "WhCosts")
plant_ports = pd.read_excel(xls, "PlantPorts")
vmi = pd.read_excel(xls, "VmiCustomers")

def clean_columns(df):
    df.columns = (df.columns.str.lower().str.strip().str.replace(" ", "_").str.replace("/", "_").str.replace("-", "_"))
    return df


orders = clean_columns(orders)
freight = clean_columns(freight)
wh_costs = clean_columns(wh_costs)
plant_ports = clean_columns(plant_ports)
vmi = clean_columns(vmi)


orders.to_sql("orders", engine, schema="supply_chain", if_exists="replace", index=False)
freight.to_sql("freight_rates", engine, schema="supply_chain", if_exists="replace", index=False)
wh_costs.to_sql("warehouse_costs", engine, schema="supply_chain", if_exists="replace", index=False)
plant_ports.to_sql("plant_ports", engine, schema="supply_chain", if_exists="replace", index=False)
vmi.to_sql("vmi_customers", engine, schema="supply_chain", if_exists="replace", index=False)

14

In [4]:
"""Orders by Origin Port"""

origin_port_summary = (orders.groupby("origin_port").agg(total_orders=("order_id", "count"),avg_weight=("weight", "mean")).reset_index().sort_values(by="total_orders", ascending=False))

origin_port_summary["avg_weight"] = origin_port_summary["avg_weight"].round(2)
origin_port_summary

  origin_port  total_orders  avg_weight
0      PORT04          9041       16.70
2      PORT09           173      185.94
1      PORT05             1        2.10

##  Generated tabular summaries to identify high-activity origin ports, highlighting key shipment hubs and so watching out that PORT04 has been the best one so far and the others need equivalent work for improvments.

In [5]:
"""Domestic vs International Shipments"""
orders["shipment_type"] = orders.apply(lambda x: "Domestic" if x["origin_port"] == x["destination_port"] else "International",axis=1)

geo_distribution = (orders.groupby("shipment_type").agg(total_orders=("order_id", "count"),avg_weight=("weight", "mean")).reset_index())

geo_distribution

   shipment_type  total_orders  avg_weight
0       Domestic           173  185.942265
1  International          9042   16.694270

##  Compared domestic and international shipments to uncover differences in volume and delivery behavior making us realise to pay more attention to domestic customers

In [6]:
"""Branches with Most Failed Deliveries"""
failed_deliveries = (orders[orders["ship_late_day_count"] > 0].groupby("plant_code").size().reset_index(name="failed_orders").sort_values(by="failed_orders", ascending=False))

failed_deliveries

  plant_code  failed_orders
0    PLANT03            174
1    PLANT08             18

##  Analyzed branch-level delivery failures to surface operational bottlenecks and thus concluding that PLANT03 needs potential improvement.

In [7]:
"""Shipment Outlier Analysis (Weight-Based)"""
mean_weight = orders["weight"].mean()
std_weight = orders["weight"].std()

outliers = orders[orders["weight"] > (mean_weight + 2 * std_weight)]

outliers[["order_id", "weight"]]

          order_id      weight
17    1.447139e+09  181.700000
18    1.447309e+09  227.200000
21    1.447352e+09  265.100000
22    1.447212e+09  267.100000
23    1.447233e+09  271.100000
...            ...         ...
8038  1.447387e+09  413.770283
8041  1.447339e+09  209.439363
8042  1.447361e+09  212.439363
8050  1.447361e+09  161.568425
8293  1.447160e+09  171.561073

[222 rows x 2 columns]

## • Identified shipment weight outliers that may increase handling complexity and logistics cost.

In [8]:
"""Shipment Charge Outlier Analysis"""
mean_charge = freight["rate"].mean()
std_charge = freight["rate"].std()

outliers = freight[freight["rate"] > (mean_charge + 2 * std_charge)]

outliers

,carrier,orig_port_cd,dest_port_cd,minm_wgh_qty,max_wgh_qty,svc_cd,minimum_cost,rate,mode_dsc,tpt_day_cnt,carrier_type
326,V444_4,PORT10,PORT09,41.281408,41.730464,DTD,7.8952,12.554687,AIR,3,V888888883_1
327,V444_4,PORT10,PORT09,41.735000,42.184056,DTD,7.9280,12.626999,AIR,3,V888888883_1
334,V444_4,PORT10,PORT09,44.910144,45.359200,DTD,9.1576,12.133181,AIR,3,V888888883_1
337,V444_4,PORT10,PORT09,46.270920,46.719976,DTD,9.2788,12.400381,AIR,3,V888888883_1
339,V444_4,PORT10,PORT09,47.178104,47.627160,DTD,9.3596,12.578515,AIR,3,V888888883_1
341,V444_4,PORT10,PORT09,48.085288,48.534344,DTD,9.4404,13.756648,AIR,3,V888888883_1
344,V444_4,PORT10,PORT09,49.446064,49.895120,DTD,9.5616,15.023849,AIR,3,V888888883_1
345,V444_4,PORT10,PORT09,49.899656,50.348712,DTD,9.6020,13.112916,AIR,3,V888888883_1
346,V444_4,PORT10,PORT09,50.353248,50.802304,DTD,9.6424,14.201983,AIR,3,V888888883_1
347,V444_4,PORT10,PORT09,50.806840,51.255896,DTD,9.6828,13.291049,AIR,3,V888888883_1
349,V444_4,PORT10,PORT09,51.714024,52.163080,DTD,9.7636,13.469183,AIR,3,V888888883_1
351,V444_4,PORT10,PORT09,52.621208,53.070264,DTD,9.8444,15.647317,AIR,3,V888888883_1
352,V444_4,PORT10,PORT09,53.074800,53.523856,DTD,9.8848,14.736384,AIR,3,V888888883_1
359,V444_4,PORT10,PORT09,56.249944,56.699000,DTD,11.1676,14.359851,AIR,3,V888888883_1
360,V444_4,PORT10,PORT09,56.703536,57.152592,DTD,11.2080,16.448918,AIR,3,V888888883_1
361,V444_4,PORT10,PORT09,57.157128,57.606184,DTD,11.2484,12.537985,AIR,3,V888888883_1
362,V444_4,PORT10,PORT09,57.610720,58.059776,DTD,11.2888,13.627052,AIR,3,V888888883_1
363,V444_4,PORT10,PORT09,58.064312,58.513368,DTD,11.3292,15.716119,AIR,3,V888888883_1
366,V444_4,PORT10,PORT09,59.425088,59.874144,DTD,11.4504,16.983319,AIR,3,V888888883_1
368,V444_4,PORT10,PORT09,60.332272,60.781328,DTD,11.5312,16.161453,AIR,3,V888888883_1
370,V444_4,PORT10,PORT09,61.239456,61.688512,DTD,11.6120,17.339586,AIR,3,V888888883_1
371,V444_4,PORT10,PORT09,61.693048,62.142104,DTD,11.6524,14.428653,AIR,3,V888888883_1
372,V444_4,PORT10,PORT09,62.146640,62.595696,DTD,11.6928,17.517720,AIR,3,V888888883_1
373,V444_4,PORT10,PORT09,62.600232,63.049288,DTD,11.7332,13.606787,AIR,3,V888888883_1
374,V444_4,PORT10,PORT09,63.053824,63.502880,DTD,11.7736,18.695854,AIR,3,V888888883_1
377,V444_4,PORT10,PORT09,64.414600,64.863656,DTD,11.8948,18.963054,AIR,3,V888888883_1
378,V444_4,PORT10,PORT09,64.868192,65.317248,DTD,11.9352,18.052121,AIR,3,V888888883_1
380,V444_4,PORT10,PORT09,65.775376,66.224432,DTD,13.0160,13.230255,AIR,3,V888888883_1
383,V444_4,PORT10,PORT09,67.136152,67.585208,DTD,13.1372,17.497455,AIR,3,V888888883_1
954,V444_7,PORT03,PORT09,0.000000,5000.000000,DTD,425.0272,128.027200,GROUND,2,V88888888_0
970,V444_5,PORT09,PORT09,0.000000,5000.000000,DTD,31.2784,21.278400,GROUND,1,V88888888_0
1489,V444_5,PORT03,PORT09,0.000000,5000.000000,DTD,27.2024,15.202400,GROUND,1,V88888888_0
1493,V444_5,PORT03,PORT09,0.000000,5000.000000,DTD,33.3172,16.317200,GROUND,1,V88888888_0
1495,V444_5,PORT03,PORT09,0.000000,5000.000000,DTD,33.3172,20.317200,GROUND,1,V88888888_0
1496,V444_5,PORT03,PORT09,0.000000,5000.000000,DTD,33.3172,13.317200,GROUND,1,V88888888_0
1497,V444_5,PORT03,PORT09,0.000000,5000.000000,DTD,27.2024,18.202400,GROUND,1,V88888888_0
1498,V444_5,PORT03,PORT09,0.000000,5000.000000,DTD,27.2024,16.202400,GROUND,1,V88888888_0
1499,V444_5,PORT03,PORT09,0.000000,5000.000000,DTD,33.3172,17.317200,GROUND,1,V88888888_0
1500,V444_0,PORT03,PORT09,0.000000,5000.000000,DTD,27.2024,16.202400,GROUND,1,V88888888_0
1502,V444_0,PORT03,PORT09,0.000000,5000.000000,DTD,25.4236,16.423600,GROUND,1,V88888888_0
1503,V444_0,PORT03,PORT09,0.000000,5000.000000,DTD,25.4236,15.423600,GROUND,1,V88888888_0
1504,V444_0,PORT03,PORT09,0.000000,5000.000000,DTD,27.2024,13.202400,GROUND,1,V88888888_0
1505,V444_0,PORT03,PORT09,0.000000,5000.000000,DTD,27.2024,13.202400,GROUND,1,V88888888_0
1507,V444_0,PORT03,PORT09,0.000000,5000.000000,DTD,33.3172,17.317200,GROUND,1,V88888888_0
1508,V444_0,PORT03,PORT09,0.000000,5000.000000,DTD,33.3172,12.317200,GROUND,1,V88888888_0
1510,V444_0,PORT03,PORT09,0.000000,5000.000000,DTD,27.2024,13.202400,GROUND,1,V88888888_0
1512,V444_5,PORT09,PORT09,0.000000,5000.000000,DTP,31.2784,20.278400,GROUND,0,V88888888_0
1513,V444_0,PORT09,PORT09,0.000000,5000.000000,DTP,31.2784,12.278400,GROUND,0,V88888888_0
1519,V444_0,PORT09,PORT09,0.000000,5000.000000,DTD,31.2784,13.278400,GROUND,0,V88888888_0

## • Detected abnormal freight charges through statistical inspection of shipment cost distributions, indicating most profitable customers

In [9]:
"""Customers with Late Shipments"""
customer_late_summary = (orders.groupby("customer").agg(total_orders=("order_id", "count"),late_shipments=("ship_late_day_count", lambda x: (x > 0).sum())).reset_index())

customer_late_summary

                  customer  total_orders  late_shipments
0   V555555555555555555_17           117               0
1   V555555555555555555_42            30               0
2   V555555555555555555_45           198               0
3   V555555555555555555_46             3               0
4      V555555555555555_23             1               0
5      V555555555555555_29           385               0
6      V555555555555555_44             9               9
7        V55555555555555_8           976               0
8        V5555555555555_16            12               0
9         V555555555555_31            45               0
10         V55555555555_28           203               0
11           V5555555555_1            22               0
12           V555555555_14           351               4
13           V555555555_27           521              69
14            V555555555_3           141               0
15           V555555555_35            14               0
16             V55555555_0           102               0
17            V55555555_32           241               0
18             V55555555_5           531               0
19             V55555555_7           618               0
20             V55555555_9            17               0
21             V5555555_12            89               0
22             V5555555_19           118               0
23             V5555555_22           693               0
24             V5555555_30           163               0
25              V555555_11            10               0
26              V555555_24           125               0
27              V555555_34            10               0
28              V555555_40             5               0
29               V555555_6           762               0
30               V55555_10            17               0
31                V55555_2           758               0
32               V55555_26           340               0
33                V55555_4           360               0
34               V55555_53           139               0
35                V5555_20            33               0
36                V5555_25            25               0
37                V5555_33           691               0
38                V5555_36            29               0
39                V5555_38             6               0
40                 V555_15           110             110
41                 V555_41            11               0
42                  V55_13           178               0
43                  V55_37             3               0
44                  V55_39             1               0
45                  V55_47             2               0

##  Evaluated customer-wise late delivery patterns to identify reliability risks and watching out for loyal customers.

In [10]:
"""High Quantity but Low Shipment Volume Customers"""
customer_summary = (orders.groupby("customer").agg(shipment_count=("order_id", "count"),total_quantity=("unit_quantity", "sum")).reset_index())

high_value_low_volume = customer_summary[(customer_summary["shipment_count"] < customer_summary["shipment_count"].median()) &(customer_summary["total_quantity"] > customer_summary["total_quantity"].median())]

high_value_low_volume

                  customer  shipment_count  total_quantity
1   V555555555555555555_42              30          470632
9         V555555555555_31              45          435868
38                V5555_36              29          931678
41                 V555_41              11          201107

## Customers that are exploiting services, not ordering much, but weight based products are peaking in value.

In [11]:
"""customer segmentation"""
def segment_customer(cnt):
    if cnt > 100:
        return "VIP"
    elif cnt > 50:
        return "Premium"
    elif cnt > 10:
        return "Regular"
    else:
        return "New"

customer_summary["segment"] = customer_summary["shipment_count"].apply(segment_customer)
customer_summary

                  customer  shipment_count  total_quantity  segment
0   V555555555555555555_17             117          266457      VIP
1   V555555555555555555_42              30          470632  Regular
2   V555555555555555555_45             198          116136      VIP
3   V555555555555555555_46               3           12080      New
4      V555555555555555_23               1             375      New
5      V555555555555555_29             385         1054980      VIP
6      V555555555555555_44               9           15125      New
7        V55555555555555_8             976          877824      VIP
8        V5555555555555_16              12            3434  Regular
9         V555555555555_31              45          435868  Regular
10         V55555555555_28             203         5293676      VIP
11           V5555555555_1              22            6441  Regular
12           V555555555_14             351          817338      VIP
13           V555555555_27             521          700796      VIP
14            V555555555_3             141           75171      VIP
15           V555555555_35              14            4512  Regular
16             V55555555_0             102           64298      VIP
17            V55555555_32             241         1914858      VIP
18             V55555555_5             531         8020417      VIP
19             V55555555_7             618          927068      VIP
20             V55555555_9              17            5091  Regular
21             V5555555_12              89           84110  Premium
22             V5555555_19             118          221362      VIP
23             V5555555_22             693          580326      VIP
24             V5555555_30             163          299830      VIP
25              V555555_11              10            6030      New
26              V555555_24             125           96177      VIP
27              V555555_34              10            6411      New
28              V555555_40               5           13072      New
29               V555555_6             762         1220461      VIP
30               V55555_10              17            6512  Regular
31                V55555_2             758         1512452      VIP
32               V55555_26             340         1909058      VIP
33                V55555_4             360          412940      VIP
34               V55555_53             139          232681      VIP
35                V5555_20              33           56705  Regular
36                V5555_25              25           48045  Regular
37                V5555_33             691          241796      VIP
38                V5555_36              29          931678  Regular
39                V5555_38               6           52801      New
40                 V555_15             110           98650      VIP
41                 V555_41              11          201107  Regular
42                  V55_13             178           93382      VIP
43                  V55_37               3            2182      New
44                  V55_39               1          100246      New
45                  V55_47               2            2724      New

##  Segmented customers based on shipment frequency and quantity for behavioral insights into new, VIP and Regular customers. Offers can be made to New customers, and Discounts can be given to old customers to retain them.

In [12]:
"""churn prediction"""
last_activity = (orders.groupby("customer")["order_date"].max().reset_index())

latest_date = orders["order_date"].max()

last_activity["days_inactive"] = (latest_date - last_activity["order_date"]).dt.days

last_activity["status"] = last_activity["days_inactive"].apply(
    lambda x: "Active" if x < 30 else "At Risk" if x < 90 else "Legacy"
)

last_activity

                  customer order_date  days_inactive  status
0   V555555555555555555_17 2013-05-26              0  Active
1   V555555555555555555_42 2013-05-26              0  Active
2   V555555555555555555_45 2013-05-26              0  Active
3   V555555555555555555_46 2013-05-26              0  Active
4      V555555555555555_23 2013-05-26              0  Active
5      V555555555555555_29 2013-05-26              0  Active
6      V555555555555555_44 2013-05-26              0  Active
7        V55555555555555_8 2013-05-26              0  Active
8        V5555555555555_16 2013-05-26              0  Active
9         V555555555555_31 2013-05-26              0  Active
10         V55555555555_28 2013-05-26              0  Active
11           V5555555555_1 2013-05-26              0  Active
12           V555555555_14 2013-05-26              0  Active
13           V555555555_27 2013-05-26              0  Active
14            V555555555_3 2013-05-26              0  Active
15           V555555555_35 2013-05-26              0  Active
16             V55555555_0 2013-05-26              0  Active
17            V55555555_32 2013-05-26              0  Active
18             V55555555_5 2013-05-26              0  Active
19             V55555555_7 2013-05-26              0  Active
20             V55555555_9 2013-05-26              0  Active
21             V5555555_12 2013-05-26              0  Active
22             V5555555_19 2013-05-26              0  Active
23             V5555555_22 2013-05-26              0  Active
24             V5555555_30 2013-05-26              0  Active
25              V555555_11 2013-05-26              0  Active
26              V555555_24 2013-05-26              0  Active
27              V555555_34 2013-05-26              0  Active
28              V555555_40 2013-05-26              0  Active
29               V555555_6 2013-05-26              0  Active
30               V55555_10 2013-05-26              0  Active
31                V55555_2 2013-05-26              0  Active
32               V55555_26 2013-05-26              0  Active
33                V55555_4 2013-05-26              0  Active
34               V55555_53 2013-05-26              0  Active
35                V5555_20 2013-05-26              0  Active
36                V5555_25 2013-05-26              0  Active
37                V5555_33 2013-05-26              0  Active
38                V5555_36 2013-05-26              0  Active
39                V5555_38 2013-05-26              0  Active
40                 V555_15 2013-05-26              0  Active
41                 V555_41 2013-05-26              0  Active
42                  V55_13 2013-05-26              0  Active
43                  V55_37 2013-05-26              0  Active
44                  V55_39 2013-05-26              0  Active
45                  V55_47 2013-05-26              0  Active

## All active customers, likely because membership date hasnot been included.

In [13]:
"""career productivity ranking"""
carrier_productivity = (orders.groupby("carrier").agg(shipments_handled=("order_id", "count"),avg_weight=("weight", "mean"),late_shipments=("ship_late_day_count", lambda x: (x > 0).sum())).reset_index())

carrier_productivity["success_rate"] = (1 - carrier_productivity["late_shipments"] / carrier_productivity["shipments_handled"])

carrier_productivity.sort_values(by="success_rate", ascending=False)

  carrier  shipments_handled  avg_weight  late_shipments  success_rate
2   V44_3                854   41.103810               0      1.000000
1  V444_1               2097   12.672628               9      0.995708
0  V444_0               6264   19.387044             183      0.970785

## Ranked logistics carriers using performance metrics derived from delivery outcomes and concluded that V44_3 is the best among all.

In [14]:
"""data quality check"""
data_quality = {"missing_origin_port": orders["origin_port"].isnull().sum(),
    "missing_destination_port": orders["destination_port"].isnull().sum(),
    "invalid_weight": (orders["weight"] <= 0).sum(),
    "missing_customer": orders["customer"].isnull().sum()
}

pd.DataFrame.from_dict(data_quality, orient="index", columns=["issue_count"])

                          issue_count
missing_origin_port                 0
missing_destination_port            0
invalid_weight                      2
missing_customer                    0

## Performed data quality checks to assess completeness and consistency before downstream analysis.